# Generated by Django 4.0.3 on 2022-03-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventaire', models.CharField(max_length=50)),
                ('num_port', models.IntegerField()),
                ('type_port', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
                ('vlan_associe', models.CharField(max_length=50)),
                ('elm_suiv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('Bloc', models.CharField(max_length=10)),
                ('Armoire', models.CharField(max_length=10)),
                ('IP', models.GenericIPAddressField()),
                ('Inventaire', models.CharField(max_length=50)),
                ('Serie', models.CharField(max_length=20)),
                ('Mac', models.CharField(max_length=17)),
                ('Nbr_port', models.IntegerField()),
                ('Nbr_port_FE', models.IntegerField()),
                ('Nbr_port_GE', models.IntegerField()),
                ('Nbr_port_SFP', models.IntegerField()),
                ('preced', models.CharField(max_length=50)),
                ('Vlans_associe', models.CharField(max_length=500)),
                ('date_achat', models.DateTimeField(verbose_name='date dachat')),
            ],
        ),
        migrations.CreateModel(
            name='vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Vlan', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('Ip', models.GenericIPAddressField()),
                ('Masque', models.CharField(max_length=50)),
                ('Passerelle', models.GenericIPAddressField()),
            ],
        ),
    ]
