# Generated by Django 4.0.3 on 2022-03-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='Armoire',
            new_name='armoire',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='Bloc',
            new_name='bloc',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='Inventaire',
            new_name='inventaire',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='Mac',
            new_name='mac',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='Serie',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='Ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='Masque',
            new_name='masque',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='Passerelle',
            new_name='passerelle',
        ),
        migrations.RemoveField(
            model_name='port',
            name='Inventaire',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='Nbr_port',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='Nbr_port_FE',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='Nbr_port_GE',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='Nbr_port_SFP',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='Vlans_associe',
        ),
        migrations.AddField(
            model_name='port',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_principal.switch'),
        ),
        migrations.AddField(
            model_name='switch',
            name='nbr_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='nbr_port_FE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='nbr_port_GE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='nbr_port_SFP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='elm_suiv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='num_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='date_achat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='modele',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='num_Vlan',
            field=models.IntegerField(default=0),
        ),
    ]
