# Generated by Django 4.0.3 on 2022-03-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_rename_armoire_switch_armoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='local',
            field=models.CharField(default='magazin', max_length=20),
        ),
    ]
