# Generated by Django 4.0.3 on 2022-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_switch_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='etat',
            field=models.CharField(choices=[('passif', 'passif'), ('actif', 'actif'), ('reformé', 'reformé')], default='passif', max_length=10),
        ),
    ]
