# Generated by Django 4.0.3 on 2022-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0006_alter_switch_armoire_alter_switch_bloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='etat',
            field=models.CharField(choices=[('defectueux', 'Defectueux'), ('utilisé', 'utilisé'), ('non_utilisé', 'Non utilisé')], default='non_utilisé', max_length=50),
        ),
        migrations.AlterField(
            model_name='switch',
            name='preced',
            field=models.CharField(blank=True, default='pas en cascade', max_length=50, verbose_name='Cascade depuis'),
        ),
    ]
