# Generated by Django 4.0.3 on 2022-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0007_alter_port_etat_alter_switch_preced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
    ]
