# Generated by Django 4.0.3 on 2022-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0012_alter_switch_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='armoire',
            field=models.CharField(default='pas configuré', max_length=25),
        ),
        migrations.AlterField(
            model_name='switch',
            name='bloc',
            field=models.CharField(default='pas configuré', max_length=25),
        ),
        migrations.AlterField(
            model_name='switch',
            name='local',
            field=models.CharField(default='magazin', max_length=25),
        ),
        migrations.AlterField(
            model_name='switch',
            name='mac',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='serie',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
