# Generated by Django 4.0.3 on 2022-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0013_alter_switch_armoire_alter_switch_bloc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
    ]
