# Generated by Django 4.0.3 on 2022-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0014_alter_switch_date_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeleswitch',
            name='nom',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nom du modèle'),
        ),
    ]
