# Generated by Django 4.0.3 on 2022-04-08 16:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0016_alter_vlan_num_vlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empcode', models.IntegerField()),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('is_active', models.IntegerField(null=True)),
            ],
            managers=[
                ('Auth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
