# Generated by Django 4.0.3 on 2022-04-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0017_tbl_authentification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Authentification',
        ),
    ]
