# Generated by Django 4.0.3 on 2022-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0018_delete_tbl_authentification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='elm_suiv',
        ),
        migrations.AddField(
            model_name='port',
            name='nom_suiv',
            field=models.CharField(default='non relié', max_length=100, verbose_name="nom de l'appareil relié"),
        ),
        migrations.AddField(
            model_name='port',
            name='type_suiv',
            field=models.CharField(choices=[('Prise', 'Prise'), ('Switch', 'Switch'), ("Point d'accés", "Point d'accés"), ('Aucun', 'Aucun'), ('Autre', 'Autre')], default='Aucun', max_length=15, verbose_name="type de l'appareil relié "),
        ),
        migrations.AlterField(
            model_name='port',
            name='type_port',
            field=models.CharField(choices=[('Prise', 'Prise'), ('Switch', 'Switch'), ("Point d'accés", "Point d'accés"), ('Aucun', 'Aucun'), ('Autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='port',
            name='vlan_associe',
            field=models.CharField(default='pas de vlan associé', max_length=50, verbose_name='VLAN associé'),
        ),
    ]
