# Generated by Django 4.0.3 on 2022-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0019_remove_port_elm_suiv_port_nom_suiv_port_type_suiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='type_port',
            field=models.CharField(choices=[('FE', 'FE'), ('GE', 'GE'), ('SFP', 'SFP')], max_length=20),
        ),
    ]
