# Generated by Django 4.0.3 on 2022-04-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0017_switch_password_switch_vlans'),
        ('app_principal', '0020_alter_port_type_port'),
    ]

    operations = [
    ]
