# Generated by Django 4.0.3 on 2022-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0021_merge_20220425_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='modele',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='switch',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='vlans',
            field=models.CharField(blank=True, default='Aucun', max_length=350, verbose_name='VLANs associés'),
        ),
    ]
