# Generated by Django 4.0.3 on 2022-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0022_alter_switch_modele_alter_switch_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
