# Generated by Django 4.0.3 on 2022-04-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0023_alter_switch_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='etat',
            field=models.CharField(choices=[('Défectueux', 'Défectueux'), ('Utilisé', 'Utilisé'), ('Non utilisé', 'Non utilisé')], default='Non utilisé', max_length=50),
        ),
        migrations.AlterField(
            model_name='port',
            name='nom_suiv',
            field=models.CharField(default='Non relié', max_length=100, verbose_name="nom de l'appareil relié"),
        ),
        migrations.AlterField(
            model_name='port',
            name='vlan_associe',
            field=models.CharField(default='Pas de VLAN', max_length=50, verbose_name='VLAN associé'),
        ),
    ]
