# Generated by Django 4.0.3 on 2022-04-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0021_contact_alter_switch_modele'),
        ('app_principal', '0024_alter_port_etat_alter_port_nom_suiv_and_more'),
    ]

    operations = [
    ]
