# Generated by Django 4.0.3 on 2022-04-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0025_merge_20220425_1524'),
        ('app_principal', '0026_alter_switch_vlans'),
    ]

    operations = [
    ]
