# Generated by Django 4.0.3 on 2022-04-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0027_merge_20220425_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='adresse_reseau',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
