# Generated by Django 4.0.3 on 2022-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0031_alter_vlan_adresse_reseau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='adresse_reseau',
            field=models.GenericIPAddressField(default='000.000.000.000'),
        ),
    ]
