# Generated by Django 4.0.3 on 2022-04-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0028_profile'),
        ('app_principal', '0034_alter_port_vlan_associe'),
    ]

    operations = [
    ]
