# Generated by Django 4.0.3 on 2022-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0035_merge_0028_profile_0034_alter_port_vlan_associe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='switchs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='local',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='vlan_associe',
            field=models.CharField(default='/', max_length=50, verbose_name='VLAN associé'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='etat',
            field=models.CharField(choices=[('Défectueux', 'Défectueux'), ('Passif', 'Passif'), ('Reformé', 'Reformé'), ('Actif', 'Actif')], default='Passif', max_length=10),
        ),
        migrations.AlterField(
            model_name='switch',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='num_Vlan',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
