# Generated by Django 4.0.3 on 2022-05-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0036_vlan_switchs_alter_port_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='switchs',
            field=models.CharField(blank=True, default='/', max_length=1000),
        ),
    ]
