# Generated by Django 4.0.3 on 2022-05-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0039_alter_switch_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
