# Generated by Django 4.0.3 on 2022-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0041_alter_port_type_suiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
