# Generated by Django 4.0.3 on 2022-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0042_alter_vlan_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='vlan_associe',
            field=models.PositiveIntegerField(default=0, verbose_name='VLAN associé'),
        ),
    ]
