# Generated by Django 4.0.3 on 2022-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0043_alter_port_vlan_associe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='nom_suiv',
            field=models.CharField(default='Non relié', max_length=100, verbose_name="Nom de l'équipement relié"),
        ),
        migrations.AlterField(
            model_name='port',
            name='type_suiv',
            field=models.CharField(choices=[('Prise', 'Prise'), ('Switch', 'Switch'), ("Point d'accés", "Point d'accés"), ('Imprimante', 'Imprimante'), ('Aucun', 'Aucun'), ('Autre', 'Autre')], default='Aucun', max_length=15, verbose_name="Type de l'équipement relié "),
        ),
        migrations.AlterField(
            model_name='port',
            name='vlan_associe',
            field=models.CharField(default='/', max_length=50, verbose_name='VLAN associé'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
